#!/usr/bin/env node
// Regenerates public/celadon-theme.js from the generator's JSON palettes
// (celadon-theme/ports/json), so the site can never drift from the theme.
//
//   npm run sync-palette                 # fetch ports/json from GitHub main
//   npm run sync-palette -- ../ports/json  # or read a local checkout
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const OUT = fileURLToPath(new URL('../public/celadon-theme.js', import.meta.url));
const RAW = 'https://raw.githubusercontent.com/celadon-theme/celadon-theme/main/ports/json/';

// Site-only metadata per variant, in display order (01–04): the default
// first, then the other darks, Sky last.
const VARIANTS = [
  { slug: 'celadon', label: 'Celadon', kind: 'dark · medium contrast', shadow: 'rgba(0,0,0,.4)|rgba(0,0,0,.5)' },
  { slug: 'celadon-powder', label: 'Powder', kind: 'dark · low contrast', shadow: 'rgba(0,0,0,.35)|rgba(0,0,0,.45)' },
  { slug: 'celadon-jade', label: 'Jade', kind: 'dark · high contrast', shadow: 'rgba(0,0,0,.5)|rgba(0,0,0,.6)' },
  { slug: 'celadon-sky', label: 'Sky', kind: 'light · sage paper', shadow: 'rgba(36,64,28,.14)|rgba(36,64,28,.18)' },
];

const ACCENTS = ['red', 'green', 'yellow', 'blue', 'magenta', 'cyan'];

const hexToRgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
const rgbToHex = (rgb) => '#' + rgb.map((v) => Math.round(v).toString(16).padStart(2, '0')).join('');
const mix = (a, b, t) => rgbToHex(hexToRgb(a).map((v, i) => v + (hexToRgb(b)[i] - v) * t));

// JSON roles → the site's --cel-* roles. `border` isn't a generator role;
// it's the overlay nudged 15% toward muted, which lands on a hairline rule
// in every variant.
function siteColors(p, shadow) {
  const [md, lg] = shadow.split('|');
  const colors = {
    bg: p.base, surface: p.surface, alt: p.overlay, border: mix(p.overlay, p.muted, 0.15),
    fg: p.text, muted: p.subtle, faint: p.muted, accent: p.green, 'accent-ink': p.base,
  };
  for (const a of ACCENTS) colors[a] = p[a];
  for (const a of ACCENTS) colors[`${a}-b`] = p[`br_${a}`];
  colors['shadow-md'] = `0 3px 10px ${md}`;
  colors['shadow-lg'] = `0 12px 32px ${lg}`;
  return colors;
}

async function loadPalette(slug, localDir) {
  const json = localDir
    ? JSON.parse(await readFile(`${localDir}/${slug}.json`, 'utf8'))
    : await fetch(`${RAW}${slug}.json`).then((res) => {
        if (!res.ok) throw new Error(`${slug}.json: HTTP ${res.status}`);
        return res.json();
      });
  for (const [role, hex] of Object.entries(json.palette)) {
    if (!/^#[0-9a-f]{6}$/i.test(hex)) throw new Error(`${slug}.json: ${role} is not a #rrggbb hex: ${hex}`);
  }
  return json;
}

const js = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

function renderVariant(v, colors) {
  const entries = Object.entries(colors).map(([k, val]) => `${/^[a-z]+$/.test(k) ? k : js(k)}: ${js(val)}`);
  const lines = [];
  for (let i = 0; i < entries.length; i += 5) lines.push('        ' + entries.slice(i, i + 5).join(', '));
  return `    ${js(v.slug)}: {
      label: ${js(v.label)}, kind: ${js(v.kind)},
      colors: {
${lines.join(',\n')}
      }
    }`;
}

const localDir = process.argv[2];
const blocks = [];
for (const v of VARIANTS) {
  const { palette } = await loadPalette(v.slug, localDir);
  blocks.push(renderVariant(v, siteColors(palette, v.shadow)));
}

const source = `/* Celadon site theming — variant palettes + live re-theme via CSS variables.
   GENERATED by scripts/sync-palette.mjs from celadon-theme/ports/json.
   Don't edit hexes here; run \`npm run sync-palette\`. */
(function () {
  var V = {
${blocks.join(',\n')}
  };
  var ORDER = [${VARIANTS.map((v) => js(v.slug)).join(', ')}];
  function stored() {
    try { var v = localStorage.getItem('celadon-variant'); return V[v] ? v : null; }
    catch (e) { return null; }
  }
  // No saved choice: follow the OS — Sky for light mode, Celadon otherwise.
  function current() {
    if (stored()) return stored();
    var light = window.matchMedia && matchMedia('(prefers-color-scheme: light)').matches;
    return light ? 'celadon-sky' : 'celadon';
  }
  function apply(name, persist) {
    var v = V[name] || V['celadon'];
    var r = document.documentElement.style;
    Object.keys(v.colors).forEach(function (k) { r.setProperty('--cel-' + k, v.colors[k]); });
    document.documentElement.setAttribute('data-celadon', name);
    var meta = document.querySelector('meta[name="theme-color"]');
    if (meta) meta.setAttribute('content', v.colors.bg);
    if (persist !== false) { try { localStorage.setItem('celadon-variant', name); } catch (e) {} }
  }
  window.CELADON = { variants: V, order: ORDER, apply: apply, current: current };
  apply(current(), false);
})();
`;

await writeFile(OUT, source);
console.log(`wrote ${OUT} (${VARIANTS.length} variants, from ${localDir || 'GitHub main'})`);
